version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: se2025
      POSTGRES_DB: appointment_db
    volumes:
      - tiberbu_postgresdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:se2025@db:5432/appointment_db
      - SECRET_KEY=s3zcz55589w9
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8002
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  tiberbu_postgresdata:
